# Pwskills

## Data Science Master

### Numpy Assignment

## Q1
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


    Yes, there is a difference in the data types of variables list_ and array_list.

    The variable list_ is a Python list, whereas array_list is a NumPy array.

    To print the data types of both variables, you can use the type() function. Here's the code:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


     This confirms that 'list_ 'is of type list and 'array_list' is of type 'numpy.ndarray'.

## Q2
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)                                                                                                                                                                                                              
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


    To print the data type of each element in both list_ and array_list, you can use a loop to iterate through the elements and apply the type() function to each element. Here's the code:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


    This code iterates through each element of 'list_' and 'array_list', and then prints the data type of each element using the 'type()' function. In 'list_', all elements are of type str. In 'array_list', the elements are of type numpy.'str_', which is the NumPy string data type.

## Q3
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


 Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


    Yes, there will be a difference in the data type of the elements present in list_ and array_list when you change the data type to int during array creation.

    Here's the modified code to print the data types of each element in both list_ and array_list after changing the data type of array_list to int:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


    In the modified code, dtype=int is used while creating 'array_list', which converts the elements to the int data type. As a result, the elements in 'array_list' are now of type numpy.int64. Meanwhile, the elements in 'list_ remain'as type str

## Q4
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


    To find the characteristics of the num_array variable, such as shape and size, you can use the following code:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Shape of num_array
print("Shape of num_array:", num_array.shape)

# (ii) Size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


 In the code above:

    (i) The shape of num_array is obtained using the shape attribute, which returns a tuple representing the dimensions of the array. In this case, the shape is (2, 3), indicating that num_array has 2 rows and 3 columns.
    
    (ii) The size of num_array is obtained using the size attribute, which returns the total number of elements in the array. In this case, the size is 6, indicating that num_array contains 6 elements in total.

## Q5
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]


    You can create a numpy array of a 3x3 matrix containing zeros only using the np.zeros() function, which takes a shape tuple as input. Here's the code to do so:

In [5]:
import numpy as np

zeros_array = np.zeros((3, 3))

print("Zeros array:\n", zeros_array)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


     In the code above, np.zeros((3, 3)) creates a numpy array of shape (3, 3) with all elements initialized to 0. This array is then assigned to the variable zeros_array. Finally, the contents of zeros_array are printed using print().






## Q6
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list) 


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

     You can create an identity matrix of shape (5, 5) using the np.identity() function in NumPy. Here's the code to create the identity matrix:

In [6]:
import numpy as np

identity_matrix = np.identity(5)

print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


    In the code above, np.identity(5) creates a 5x5 identity matrix where the diagonal elements are 1 and all other elements are 0. This identity matrix is then assigned to the variable identity_matrix. Finally, the content of identity_matrix is printed using print().